replicaCount: 1

imagePullPolicy: IfNotPresent

backend:
  image: infos-backend:latest
  port: 8080
  resources: {}

frontend:
  image: infos-frontend:latest
  port: 80
  resources: {}

mysql:
  host: infos-mysql.infos-db.svc.cluster.local
  port: 3306
  username: root
  password: root
  database: atomic
  waitImage: mysql:8.4

kafka:
  image: apache/kafka:4.3.0
  port: 9092
  topic: demo-topic
  resources: {}

ingress:
  enabled: true
  className: nginx
  host: infos.local
  paths:
    frontend: /
    backend: /api